spring.application.name=sb-ecom
server.port=8081
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:256c9a32-6e7d-4b6c-a138-fa1a8fdb512a
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.ddl-auto=update